### ISSUE TITLE
Incorrect oneTBB Spec version macro

### ISSUE THREAD

**Issue by omalyshe** [uxlfoundation/oneAPI-spec#253]
On [the page](https://spec.oneapi.com/versions/latest/elements/oneTBB/source/configuration/version_information.html) ONETBB_SPEC_VERSION must be instead of TBB_SPEC_VERSION. 
And its value should be in "", that is 
`#define ONETBB_SPEC_VERSION "1.0"`

**Comment by akukanov** [comment]
Finally resolved by https://github.com/uxlfoundation/oneAPI-spec/pull/592
