### ISSUE TITLE
[OneMKL] definition of `m` and `n` parameters in `gemv_batch`

### ISSUE THREAD

**Issue by vtavana** [uxlfoundation/oneAPI-spec#531]
In the description of `gemv_batch`, it is stated that `m` is "Number of rows of op(``A``)."
https://github.com/oneapi-src/oneAPI-spec/blob/main/source/elements/oneMKL/source/domains/blas/gemv_batch.rst?plain=1#L431

However, I believe it should be Number of rows of ``A`` similar to its `gemv` counterpart: https://github.com/oneapi-src/oneAPI-spec/blob/main/source/elements/oneMKL/source/domains/blas/gemv.rst?plain=1#L221

Similar modification should be made for parameter `n` and in all variants of `gemv_batch`.

**Comment by mmeterel** [comment]
@vtavana Thanks for posting the issue. Fix submitted #532

**Comment by mmeterel** [comment]
@vtavana  I think this can be closed now?
