### ISSUE TITLE
[OneMKL] [BLAS] data type of `transa` and `transb` in `gemm` and `gemv`

### ISSUE THREAD

**Issue by vtavana** [uxlfoundation/oneAPI-spec#534]
Should `oneapi::mkl::transpose` be used instead of `onemkl::transpose` as the data type of `transa` and `transb` in `gemm`, `gemm_batch`, `gemv`, and `gemv_batch`? If yes, the change should be applied to all variants of each function.

For instance, here 
https://github.com/uxlfoundation/oneAPI-spec/blob/main/source/elements/oneMKL/source/domains/blas/gemm.rst?plain=1#L104

**Comment by mmeterel** [comment]
@vtavana  Yes thanks for pointing is out. The namespaces needs to be updated in all relevant APIs. 
Feel free to open a pull request if you would like.

**Comment by andrewtbarker** [comment]
Fixed in #535
